# .slather.yml

ci_service: travis_ci
coverage_service: coveralls
xcodeproj: SwiftRepositories/SwiftRepositories.xcodeproj
workspace: SwiftRepositories/SwiftRepositories.xcworkspace
scheme: SwiftRepositories
source_directory: SwiftRepositories/
ignore:	
  - ExamplePodCode/*
  - ProjectTestsGroup/*
